#!/bin/bash
# vim: set ft=bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$TMPDIR/myip-resource-request

cat > "$payload" <&0

version_object=$(jq -r '.version // "{}"' < "$payload")
ip=$(jq -r '.version.ip // ""' < "$payload")

mkdir -p "$1"
cd "$1"
echo "$ip" >> ip

jq -c -n \
    --argjson version_object "$version_object" \
    '{
        "version": $version_object
    }' >&3
